//> using publish.name "test-util"
//> using publish.ci.computeVersion "git:tag"
//> using publish.ci.repository "central-s01"
//> using publish.ci.user "env:PUBLISH_USER"
//> using publish.ci.password "env:PUBLISH_PASSWORD"
//> using publish.ci.secretKey "env:PUBLISH_SECRET_KEY"
//> using publish.ci.secretKeyPassword "env:PUBLISH_SECRET_KEY_PASSWORD"
//> using publish.ci.publicKey "env:PUBLISH_PUBLIC_KEY"
//> using publish.license "Apache-2.0"
//> using publish.url "https://github.com/alexarchambault/test-util"
//> using publish.versionControl "github:alexarchambault/test-util"
//> using publish.developer "Alex Archambault||https://github.com/alexarchambault"
